apiVersion: v1
kind: Service
metadata:
  name: meeting-bot
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: meeting-bot
  ports:
    - port: {{ .Values.bot.port }}
      targetPort: {{ .Values.bot.port }}
      protocol: TCP
      name: http
