apiVersion: v1
kind: Secret
metadata:
  name: meeting-webhook-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  RECALL_WORKSPACE_VERIFICATION_SECRET: {{ .Values.env.RECALL_WORKSPACE_VERIFICATION_SECRET | quote }}
