apiVersion: v1
kind: Service
metadata:
  name: meeting-auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: meeting-auth
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      protocol: TCP
      name: http
