# helm-meeting-calendar/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: meeting-calendar-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | quote }}
  ENCRYPTION_KEY: {{ .Values.env.ENCRYPTION_KEY | quote }}
