apiVersion: v1
kind: Secret
metadata:
  name: pg-auth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_PASSWORD: {{ required "postgres.password is required" .Values.postgres.password }}
